spring.application.name=notesDb

server.port=5000

spring.config.import=aws-parameterstore:/config/notes_db

# Expect parameters in AWS Parameter Store
# /config/notest_db/spring.datasource.url
#   -> MySQL DB URL:  jdbc:mysql://<database-dns-name>/notes_db
# /config/notest_db/spring.datasource.username
# /config/notest_db/spring.datasource.password
