spring.application.name=notesDb

spring.datasource.url=jdbc:mysql://database-1.c9mkgbdsmou4.eu-central-1.rds.amazonaws.com:3306/notes_db
spring.datasource.username=notesuser
spring.datasource.password=notes1pass
